name: Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHONFORANDROID_PREREQUISITES_INSTALL_INTERACTIVE: "0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install .

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt -y install automake libltdl-dev

      - name: Check Buildozer
        run: |
          buildozer --help

      - name: Prepare Android
        run: |
          sed -i.bak \
            "s/# android.accept_sdk_license = False/android.accept_sdk_license = True/" \
            buildozer.spec

          sed -i.bak \
            "s/#p4a.branch = master/p4a.branch = develop/" \
            buildozer.spec

          buildozer android p4a -- --help

      - name: Build APK
        run: |
          test -f main.py
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Detecteur-Spam-APK
          path: bin/*.apk
          if-no-files-found: error
